const PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED";

const RESEARCH_CREATED = "RESEARCH_CREATED";
const RESEARCH_PROPOSED = "RESEARCH_PROPOSED";
const RESEARCH_PROPOSAL_SIGNED = "RESEARCH_PROPOSAL_SIGNED";
const RESEARCH_PROPOSAL_REJECTED = "RESEARCH_PROPOSAL_REJECTED";

const RESEARCH_UPDATED = "RESEARCH_UPDATED";
const RESEARCH_UPDATE_PROPOSED = "RESEARCH_UPDATE_PROPOSED";
const RESEARCH_UPDATE_PROPOSAL_SIGNED = "RESEARCH_UPDATE_PROPOSAL_SIGNED";
const RESEARCH_UPDATE_PROPOSAL_REJECTED = "RESEARCH_UPDATE_PROPOSAL_REJECTED";

const RESEARCH_MATERIAL_PROPOSED = "RESEARCH_MATERIAL_PROPOSED";
const RESEARCH_MATERIAL_CREATED = "RESEARCH_MATERIAL_CREATED";

const RESEARCH_GROUP_CREATED = "RESEARCH_GROUP_CREATED";

const RESEARCH_GROUP_UPDATED = "RESEARCH_GROUP_UPDATED";
const RESEARCH_GROUP_UPDATE_PROPOSED = "RESEARCH_GROUP_UPDATE_PROPOSED";
const RESEARCH_GROUP_UPDATE_PROPOSAL_SIGNED = "RESEARCH_GROUP_UPDATE_PROPOSAL_SIGNED";
const RESEARCH_GROUP_UPDATE_PROPOSAL_REJECTED = "RESEARCH_GROUP_UPDATE_PROPOSAL_REJECTED";

const RESEARCH_APPLICATION_CREATED = "RESEARCH_APPLICATION_CREATED";
const RESEARCH_APPLICATION_APPROVED = "RESEARCH_APPLICATION_APPROVED";
const RESEARCH_APPLICATION_REJECTED = "RESEARCH_APPLICATION_REJECTED";
const RESEARCH_APPLICATION_EDITED = "RESEARCH_APPLICATION_EDITED";
const RESEARCH_APPLICATION_DELETED = "RESEARCH_APPLICATION_DELETED";
const USER_INVITATION_PROPOSED = "USER_INVITATION_PROPOSED";
const USER_INVITATION_SIGNED = "USER_INVITATION_SIGNED";
const USER_INVITATION_CANCELED = "USER_INVITATION_CANCELED";
const USER_RESIGNATION_PROPOSED = "USER_RESIGNATION_PROPOSED";
const USER_RESIGNATION_SIGNED = "USER_RESIGNATION_SIGNED";
const USER_RESIGNATION_CANCELED = "USER_RESIGNATION_CANCELED";
const RESEARCH_TOKEN_SALE_PROPOSED = "RESEARCH_TOKEN_SALE_PROPOSED";
const RESEARCH_TOKEN_SALE_CREATED = "RESEARCH_TOKEN_SALE_CREATED";
const RESEARCH_EXPRESS_LICENSE_REQUEST_CREATED = "RESEARCH_EXPRESS_LICENSE_REQUEST_CREATED";
const RESEARCH_EXPRESS_LICENSE_REQUEST_SIGNED = "RESEARCH_EXPRESS_LICENSE_REQUEST_SIGNED";
const RESEARCH_EXPRESS_LICENSE_REQUEST_CANCELED = "RESEARCH_EXPRESS_LICENSE_REQUEST_CANCELED";
const ASSET_EXCHANGE_PROPOSED = "ASSET_EXCHANGE_PROPOSED";
const ASSET_EXCHANGE_PROPOSAL_SIGNED = "ASSET_EXCHANGE_PROPOSAL_SIGNED";
const ASSET_EXCHANGE_PROPOSAL_REJECTED = "ASSET_EXCHANGE_PROPOSAL_REJECTED";
const ASSET_TRANSFERRED = "ASSET_TRANSFERRED";

const ASSET_TRANSFER_PROPOSED = "ASSET_TRANSFER_PROPOSED";
const ASSET_TRANSFER_PROPOSAL_SIGNED = "ASSET_TRANSFER_PROPOSAL_SIGNED";
const ASSET_TRANSFER_PROPOSAL_REJECTED = "ASSET_TRANSFER_PROPOSAL_REJECTED";

const APP_EVENTS = {
  PROPOSAL_ACCEPTED,
  
  RESEARCH_CREATED,
  RESEARCH_PROPOSED,
  RESEARCH_PROPOSAL_SIGNED,
  RESEARCH_PROPOSAL_REJECTED,
  
  RESEARCH_UPDATED,
  RESEARCH_UPDATE_PROPOSED,
  RESEARCH_UPDATE_PROPOSAL_SIGNED,
  RESEARCH_UPDATE_PROPOSAL_REJECTED,

  RESEARCH_MATERIAL_PROPOSED,
  RESEARCH_MATERIAL_CREATED,

  RESEARCH_GROUP_CREATED,

  RESEARCH_GROUP_UPDATED,
  RESEARCH_GROUP_UPDATE_PROPOSED,
  RESEARCH_GROUP_UPDATE_PROPOSAL_SIGNED,
  RESEARCH_GROUP_UPDATE_PROPOSAL_REJECTED,

  RESEARCH_APPLICATION_CREATED,
  RESEARCH_APPLICATION_APPROVED,
  RESEARCH_APPLICATION_REJECTED,
  RESEARCH_APPLICATION_EDITED,
  RESEARCH_APPLICATION_DELETED,
  USER_INVITATION_PROPOSED,
  USER_INVITATION_SIGNED,
  USER_INVITATION_CANCELED,
  USER_RESIGNATION_PROPOSED,
  USER_RESIGNATION_SIGNED,
  USER_RESIGNATION_CANCELED,
  RESEARCH_TOKEN_SALE_PROPOSED,
  RESEARCH_TOKEN_SALE_CREATED,
  RESEARCH_EXPRESS_LICENSE_REQUEST_CREATED,
  RESEARCH_EXPRESS_LICENSE_REQUEST_SIGNED,
  RESEARCH_EXPRESS_LICENSE_REQUEST_CANCELED,
  
  ASSET_EXCHANGE_PROPOSED,
  ASSET_EXCHANGE_PROPOSAL_SIGNED,
  ASSET_EXCHANGE_PROPOSAL_REJECTED,
  
  ASSET_TRANSFERRED,
  ASSET_TRANSFER_PROPOSED,
  ASSET_TRANSFER_PROPOSAL_SIGNED,
  ASSET_TRANSFER_PROPOSAL_REJECTED
}

export default APP_EVENTS;