const PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED";
const RESEARCH_PROPOSED = "RESEARCH_PROPOSED";
const RESEARCH_CREATED = "RESEARCH_CREATED";
const RESEARCH_MATERIAL_PROPOSED = "RESEARCH_MATERIAL_PROPOSED";
const RESEARCH_MATERIAL_CREATED = "RESEARCH_MATERIAL_CREATED";

const APP_EVENTS = {
  PROPOSAL_ACCEPTED,
  RESEARCH_PROPOSED,
  RESEARCH_CREATED,
  RESEARCH_MATERIAL_PROPOSED,
  RESEARCH_MATERIAL_CREATED
}

export default APP_EVENTS;