const PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED";
const RESEARCH_PROPOSED = "RESEARCH_PROPOSED";
const RESEARCH_CREATED = "RESEARCH_CREATED";
const RESEARCH_MATERIAL_PROPOSED = "RESEARCH_MATERIAL_PROPOSED";
const RESEARCH_MATERIAL_CREATED = "RESEARCH_MATERIAL_CREATED";
const RESEARCH_UPDATE_PROPOSED = "RESEARCH_UPDATE_PROPOSED";
const RESEARCH_UPDATED = "RESEARCH_UPDATED";
const RESEARCH_GROUP_CREATED = "RESEARCH_GROUP_CREATED";
const RESEARCH_GROUP_UPDATE_PROPOSED = "RESEARCH_GROUP_UPDATE_PROPOSED";
const RESEARCH_GROUP_UPDATED = "RESEARCH_GROUP_UPDATED";
const RESEARCH_APPLICATION_CREATED = "RESEARCH_APPLICATION_CREATED";
const RESEARCH_APPLICATION_APPROVED = "RESEARCH_APPLICATION_APPROVED";
const RESEARCH_APPLICATION_REJECTED = "RESEARCH_APPLICATION_REJECTED";
const RESEARCH_APPLICATION_EDITED = "RESEARCH_APPLICATION_EDITED";
const RESEARCH_APPLICATION_DELETED = "RESEARCH_APPLICATION_DELETED";
const USER_INVITATION_CREATED = "USER_INVITATION_CREATED";
const USER_INVITATION_SIGNED = "USER_INVITATION_SIGNED";
const USER_INVITATION_CANCELED = "USER_INVITATION_CANCELED";

const APP_EVENTS = {
  PROPOSAL_ACCEPTED,
  RESEARCH_PROPOSED,
  RESEARCH_CREATED,
  RESEARCH_MATERIAL_PROPOSED,
  RESEARCH_MATERIAL_CREATED,
  RESEARCH_UPDATE_PROPOSED,
  RESEARCH_UPDATED,
  RESEARCH_GROUP_CREATED,
  RESEARCH_GROUP_UPDATE_PROPOSED,
  RESEARCH_GROUP_UPDATED,
  RESEARCH_APPLICATION_CREATED,
  RESEARCH_APPLICATION_APPROVED,
  RESEARCH_APPLICATION_REJECTED,
  RESEARCH_APPLICATION_EDITED,
  RESEARCH_APPLICATION_DELETED,
  USER_INVITATION_CREATED,
  USER_INVITATION_SIGNED,
  USER_INVITATION_CANCELED
}

export default APP_EVENTS;