
const START_RESEARCH = 1;
const INVITE_MEMBER = 2;
const DROPOUT_MEMBER = 3;
const SEND_FUNDS = 4;
const START_RESEARCH_TOKEN_SALE = 5;
const REBALANCE_RESEARCH_GROUP_TOKENS = 6;
const CHANGE_QUORUM = 7;
const CHANGE_RESEARCH_REVIEW_SHARE_PERCENT = 8;
const OFFER_RESEARCH_TOKENS = 9;
const CREATE_RESEARCH_MATERIAL = 10;
const CHANGE_RESEARCH_GROUP_META_DATA_TYPE = 11;
const CHANGE_RESEARCH_META_DATA_TYPE = 12;

const PROPOSAL_TYPE = {
  START_RESEARCH,
  INVITE_MEMBER,
  DROPOUT_MEMBER,
  SEND_FUNDS,
  START_RESEARCH_TOKEN_SALE,
  REBALANCE_RESEARCH_GROUP_TOKENS,
  CHANGE_QUORUM,
  CHANGE_RESEARCH_REVIEW_SHARE_PERCENT,
  OFFER_RESEARCH_TOKENS,
  CREATE_RESEARCH_MATERIAL,
  CHANGE_RESEARCH_GROUP_META_DATA_TYPE,
  CHANGE_RESEARCH_META_DATA_TYPE
}

export default PROPOSAL_TYPE;