const USER_RESIGNATION_PROPOSED = "USER_RESIGNATION_PROPOSED";
const USER_RESIGNATION_PROPOSAL_SIGNED = "USER_RESIGNATION_PROPOSAL_SIGNED";
const USER_RESIGNATION_PROPOSAL_REJECTED = "USER_RESIGNATION_PROPOSAL_REJECTED";

const RESEARCH_EXPRESS_LICENSE_PROPOSED = "RESEARCH_EXPRESS_LICENSE_PROPOSED";
const RESEARCH_EXPRESS_LICENSE_PROPOSAL_SIGNED = "RESEARCH_EXPRESS_LICENSE_PROPOSAL_SIGNED";
const RESEARCH_EXPRESS_LICENSE_PROPOSAL_REJECTED = "RESEARCH_EXPRESS_LICENSE_PROPOSAL_REJECTED";


const LEGACY_APP_EVENTS = {

  USER_RESIGNATION_PROPOSED,
  USER_RESIGNATION_PROPOSAL_SIGNED,
  USER_RESIGNATION_PROPOSAL_REJECTED,

  RESEARCH_EXPRESS_LICENSE_PROPOSED,
  RESEARCH_EXPRESS_LICENSE_PROPOSAL_SIGNED,
  RESEARCH_EXPRESS_LICENSE_PROPOSAL_REJECTED
}

export default LEGACY_APP_EVENTS;