const RESEARCH_CONTENT_CREATED = "RESEARCH_CONTENT_CREATED"; 
const RESEARCH_CONTENT_PROPOSED = "RESEARCH_CONTENT_PROPOSED";
const RESEARCH_CONTENT_PROPOSAL_SIGNED = "RESEARCH_CONTENT_PROPOSAL_SIGNED";
const RESEARCH_CONTENT_PROPOSAL_REJECTED = "RESEARCH_CONTENT_PROPOSAL_REJECTED";

const RESEARCH_APPLICATION_CREATED = "RESEARCH_APPLICATION_CREATED";
const RESEARCH_APPLICATION_APPROVED = "RESEARCH_APPLICATION_APPROVED";
const RESEARCH_APPLICATION_REJECTED = "RESEARCH_APPLICATION_REJECTED";
const RESEARCH_APPLICATION_EDITED = "RESEARCH_APPLICATION_EDITED";
const RESEARCH_APPLICATION_DELETED = "RESEARCH_APPLICATION_DELETED";

const USER_RESIGNATION_PROPOSED = "USER_RESIGNATION_PROPOSED";
const USER_RESIGNATION_PROPOSAL_SIGNED = "USER_RESIGNATION_PROPOSAL_SIGNED";
const USER_RESIGNATION_PROPOSAL_REJECTED = "USER_RESIGNATION_PROPOSAL_REJECTED";

const RESEARCH_EXPRESS_LICENSE_PROPOSED = "RESEARCH_EXPRESS_LICENSE_PROPOSED";
const RESEARCH_EXPRESS_LICENSE_PROPOSAL_SIGNED = "RESEARCH_EXPRESS_LICENSE_PROPOSAL_SIGNED";
const RESEARCH_EXPRESS_LICENSE_PROPOSAL_REJECTED = "RESEARCH_EXPRESS_LICENSE_PROPOSAL_REJECTED";

const RESEARCH_NDA_PROPOSED = "RESEARCH_NDA_PROPOSED";
const RESEARCH_NDA_PROPOSAL_SIGNED = "RESEARCH_NDA_PROPOSAL_SIGNED";
const RESEARCH_NDA_PROPOSAL_REJECTED = "RESEARCH_NDA_PROPOSAL_REJECTED";

const LEGACY_APP_EVENTS = {
  RESEARCH_CONTENT_CREATED,
  RESEARCH_CONTENT_PROPOSED,
  RESEARCH_CONTENT_PROPOSAL_SIGNED,
  RESEARCH_CONTENT_PROPOSAL_REJECTED,

  RESEARCH_APPLICATION_CREATED,
  RESEARCH_APPLICATION_APPROVED,
  RESEARCH_APPLICATION_REJECTED,
  RESEARCH_APPLICATION_EDITED,
  RESEARCH_APPLICATION_DELETED,

  USER_RESIGNATION_PROPOSED,
  USER_RESIGNATION_PROPOSAL_SIGNED,
  USER_RESIGNATION_PROPOSAL_REJECTED,

  RESEARCH_EXPRESS_LICENSE_PROPOSED,
  RESEARCH_EXPRESS_LICENSE_PROPOSAL_SIGNED,
  RESEARCH_EXPRESS_LICENSE_PROPOSAL_REJECTED,

  RESEARCH_NDA_PROPOSED,
  RESEARCH_NDA_PROPOSAL_SIGNED,
  RESEARCH_NDA_PROPOSAL_REJECTED,
}

export default LEGACY_APP_EVENTS;