const CREATE_RESEARCH = 1;
const UPDATE_RESEARCH = 2;
const CREATE_RESEARCH_CONTENT = 3;
const CREATE_RESEARCH_TOKEN_SALE = 4;
const UPDATE_RESEARCH_GROUP = 5;
const INVITE_MEMBER = 6;
const EXCLUDE_MEMBER = 7;
const ASSET_TRANSFER = 8;
const EXPRESS_LICENSE_REQUEST = 9;
const ASSET_EXCHANGE = 10;
const RESEARCH_NDA = 11;


const SMART_CONTRACT_TYPE = {
  CREATE_RESEARCH,
  UPDATE_RESEARCH,
  CREATE_RESEARCH_CONTENT,
  CREATE_RESEARCH_TOKEN_SALE,
  UPDATE_RESEARCH_GROUP,
  INVITE_MEMBER,
  EXCLUDE_MEMBER,
  ASSET_TRANSFER,
  EXPRESS_LICENSE_REQUEST,
  ASSET_EXCHANGE,
  RESEARCH_NDA
};


export default SMART_CONTRACT_TYPE;