import { createEnum } from '@deip/toolbox';


const APP_EVENT = createEnum({
  PROJECT_CREATED: 1,
  PROJECT_UPDATED: 2,
  PROJECT_MEMBER_JOINED: 3,

  PROPOSAL_CREATED: 4,
  PROPOSAL_UPDATED: 5,
  PROPOSAL_DECLINED: 6,

  TEAM_CREATED: 7,

  PROJECT_INVITE_CREATED: 8,
  PROJECT_INVITE_ACCEPTED: 9,
  PROJECT_INVITE_DECLINED: 10,

  PROJECT_PROPOSAL_CREATED: 11,
  PROJECT_PROPOSAL_ACCEPTED: 12,
  PROJECT_PROPOSAL_DECLINED: 13,

  PROJECT_UPDATE_PROPOSAL_CREATED: 14,
  PROJECT_UPDATE_PROPOSAL_ACCEPTED: 15,
  PROJECT_UPDATE_PROPOSAL_DECLINED: 16
});


module.exports = APP_EVENT;